### ISSUE TITLE
drawtext for the menu?

### ISSUE THREAD

**Issue by ItssJxstnDe** [Sqrl34/sqrl-nightclubs#2]
Its annoying to go away and back to buy stuff

**Comment by ItssJxstnDe** [comment]
Btw; 
![image](https://github.com/Sqrl34/sqrl-nightclubs/assets/127620206/4d7cb219-b332-45f0-bab9-444c0ebf4129)

Using OFC Qbcore

**Comment by ItssJxstnDe** [comment]
![image](https://github.com/Sqrl34/sqrl-nightclubs/assets/127620206/21a17f3d-6409-4f3b-a1d4-f99cbf4c1b90)

**Comment by Sqrl34** [comment]
Hi, Can you explain what you were doing when the second error occured as I am having trouble replicating it. As for the one above, next update it will be fixed but currently does not affect anything right now. As for the comment, it is only possible to have it like that because the data does not have time to update in real time from when the ipl gets reloaded with the new set of designs. Thank you for using the resource

**Comment by Sqrl34** [comment]
I could however see about implementing a config for drawtext in the future but for now it is just with polyzones

**Comment by ItssJxstnDe** [comment]
ok whould be cool

**Comment by ItssJxstnDe** [comment]
> Hi, Can you explain what you were doing when the second error occured as I am having trouble replicating it. As for the one above, next update it will be fixed but currently does not affect anything right now. As for the comment, it is only possible to have it like that because the data does not have time to update in real time from when the ipl gets reloaded with the new set of designs. Thank you for using the resource



Idk what im doing we change some Upgrades

**Comment by Sqrl34** [comment]
Did you ever find out what you were doing as I can not replicate the error after numerous tests

**Comment by ItssJxstnDe** [comment]
nope

**Comment by Sqrl34** [comment]
should be fixed in the 1.1 Update, please re download and let me know if there are any other errors. Both should be fixed

**Comment by Sqrl34** [comment]
may I close this issue or have you found more? @ItssJxstnDe
